version: "3.8"

services:
  apoiaserver:
    user: root
    container_name: apoiaserver
    build: .
    depends_on:
      - apoiamysql
    ports:
      - "8080:3000"
    env_file:
      - .env.local
    networks:
      - apoia

  apoiamysql:
    container_name: apoiamysql
    image: mysql:8.0.21
    restart: always
    expose:
      - "3306"
    ports:
      - 5001:3306
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "apoia"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./migration-001.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apoia
    #   - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: {}

networks:
  apoia:
