---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuracao-web-config
  labels:
    app: configuracao-web
    part-of: pdpj-configuracao-web
data:
  config.json: |
    {
      "name": "local",
      "production": true,
      "api": {},
      "authentication": {}
    }

  env.js: |
    (function (window) {
      window.__env = window.__env || {};
      window.__env.production = true;
      window.__env.nome = "Configuração Web";
      window.__env.descricao = "Configuração Web - Front-End do Módulo de Configuração";
      window.__env.apiUrl = "https://gateway.cloud.pje.jus.br/configuracao/api/v1",
      window.__env.ssoUrl = "https://sso.cloud.pje.jus.br/auth/",
      window.__env.realm = "pje",
      window.__env.clientId = "configuracao-web-client-id",
      window.__env.redirectUri = "https://configuracao.pdpj.jus.br"
    }(this));
...
