apiVersion: apps/v1
kind: Deployment
metadata:
  name: apoia
  labels:
    app: pdpj-apoia
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: pdpj-apoia
  template:
    metadata:
      labels:
        app: pdpj-apoia
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: pdpj-apoia
              topologyKey: kubernetes.io/hostname
      containers:
      - name: apoia
        image: registry.cnj.jus.br/pdpj/apoia:latest
        imagePullPolicy: Always
        env:
          - name: TZ
            value: America/Sao_Paulo
        envFrom:
        - secretRef:
            name: apoia-db-secret
        - secretRef:
            name: apoia-envs-secret
        - secretRef:
            name: apoia-keycloak-secret
        - configMapRef:
            name: apoia-config
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: http
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: http
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10  
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        #volumeMounts:
        #- name: apoia-config
        #  mountPath: /app/config/
        #  readOnly: true
      imagePullSecrets:
      - name: registry-cnj
      #volumes:
      #- name: apoia-config
      #  configMap:
      #    name: apoia-config

---
apiVersion: v1
kind: Service
metadata:
  name: apoia
  labels:
    app: pdpj-apoia
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: pdpj-apoia
