---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apoia-config
  labels:
    app: apoia
    part-of: pdpj-apoia
data:
  .env.local: |
    NEXTAUTH_URL_INTERNAL=http://localhost:80
    NEXTAUTH_URL=http://apoia.stg.pdpj.jus.br
    NEXTAUTH_SECRET=***SUBSTITUIR_POR_UMA_SENHA_SEGURA***

    JWT_SECRET=***SUBSTITUIR_POR_UMA_SENHA_SEGURA***
    JWT_ISSUER=apoia.trf2.jus.br
    JWT_AUDIENCE=apoia.trf2.jus.br

    PWD_SECRET=***SUBSTITUIR_POR_UMA_SENHA_SEGURA***

    COMPLETE_ANALYSIS_LIMIT=10000

    CONFIDENTIALITY_LEVEL_MAX=0

    VERCEL="1"
    VERCEL_ENV="production"

    DB_CLIENT=pg
    DB_HOST=localhost
    DB_PORT=5432
    DB_USER=postgres
    DB_PASSWORD=***SUBSTITUIR_POR_UMA_SENHA_SEGURA***
    DB_DATABASE=apoia

    KEYCLOAK_ID=apoia
    KEYCLOAK_SECRET=***SUBSTITUIR_POR_UMA_SENHA_SEGURA***
    KEYCLOAK_ISSUER=https://sso.cloud.pje.jus.br/realms/pdpj
        
    APP_CODE=ApoIA
    APP_HOST=https://apoia.stg.pdpj.jus.br
    APP_PORT=80
    APP_REGISTRY_HOST=https://discovery.stg.cloud.pje.jus.br/eureka
    APP_REGISTRY_PORT=80
...
