apiVersion: v1
kind: ConfigMap
metadata:
  name: apoia-config
  labels:
    app: apoia
    part-of: pdpj-apoia
data:
  NEXTAUTH_URL_INTERNAL: "http://localhost:80"
  NEXTAUTH_URL: "http://apoia.stg.pdpj.jus.br"
  ###NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

  ###JWT_SECRET: ${JWT_SECRET}
  JWT_ISSUER: "apoia.trf2.jus.br"
  JWT_AUDIENCE: "apoia.trf2.jus.br"
  ###PWD_SECRET: ${PWD_SECRET}
  
  COMPLETE_ANALYSIS_LIMIT: "10000"
  CONFIDENTIALITY_LEVEL_MAX: "0"
  VERCEL: "1"
  VERCEL_ENV: "development"
  
  DB_CLIENT: "pg"
  DB_HOST: "postgres.comum-homologacao"
  DB_PORT: "5432"
  #DB_USER: ${DB_USER}
  #DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE: "pdpj_apoia"

  ###KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CREDENTIALS_SECRET}
  KEYCLOAK_ISSUER: "https://sso.stg.cloud.pje.jus.br/auth/realms/pje"
  
  APP_CODE: "ApoIA"
  APP_HOST: "apoia.stg.pdpj.jus.br"
  APP_PORT: "80"
  APP_REGISTRY_HOST: "discovery.stg.cloud.pje.jus.br/eureka"
  # APP_REGISTRY_PORT: "8761"

  DATALAKE_API_URL: "https://api-processo.stg.data-lake.pdpj.jus.br/processo-api/api/v1"
  
  # SYSTEMS: "TRF2,JFRJ,JFES"
  # TRF2_MNI_WSDL_URL: "https://eproc-ws.trf2.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # TRF2_MNI_ENDPOINT_URL: "https://eproc-ws.trf2.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  # JFRJ_MNI_WSDL_URL: "https://eproc-ws.jfrj.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # JFRJ_MNI_ENDPOINT_URL: "https://eproc-ws.jfrj.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"
  # JFES_MNI_WSDL_URL: "https://eproc-ws.jfes.jus.br/eproc/wsdl.php?srv=intercomunicacao2.2"
  # JFES_MNI_ENDPOINT_URL: "https://eproc-ws.jfes.jus.br/eproc/ws/controlador_ws.php?srv=intercomunicacao2.2"

  MODERATOR: "00489623760"

  MODEL: "gpt-4.1-nano"
  OPENAI_API_KEY_ENCRYPTED: "01932d9d42ef35fcf537d7011c32eeefc229509c2a2c308489a0584196d4917039fcb714d3e754b592cfc558c8a9d6bfe4cb878c180a68f81f8c51052678ae43528080e81415b075921f196e2eb38690013093837a458d6e9356fde8537daa762151de7b85b66c3e600334d86654e6be4680ed27b703df3c126cd28e4e8d618f2acdbadaecb824e010571fb1092bffa9c25867b8be91188c51c7d55621c0aad5d111374fe08b03253cbc7cc2c7bf57277c3a1a6fc8f49d5dbc3c8029e9e32b537a3eb1221e46e4524fdb18f15f702b10b6d7f8743e7c8efbb4b08e2c20ae80307a205d8be0d6d20e9649913a7e8fc84d4cb167056a9305989418c555f96828de4a046ac5"

