apiVersion: v1
kind: ConfigMap
metadata:
  name: apoia-config
  labels:
    app: apoia
data:
  application.yaml: |
    spring:
      application:
        name: apoia
      jackson:
        time-zone: Brazil/East
        locale: pt-BR
    server:
      port: 8080

    datasource:
      url: jdbc:postgresql://postgres.comum-homologacao/pdpj_apoia
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      hikari:
        pool-name: ApoiaHCP_HML
        connection-timeout: 5000
        maximum-pool-size: 15
        idle-timeout: 10000 # Tempo máximo em milissegundos que uma conexão pode ficar ociosa
        minimum-idle: 3 # Número mínimo de conexões em estado "idle"    
    jpa:
      generate-ddl: false
      show-sql: false
      hibernate:
        ddl-auto: none ### update, create, create-drop
      properties:
        hibernate:
          default_schema: apoia
          format_sql: true
        org:
          hibernate:
            envers:
              default_schema: audit
    flyway:
      url: ${spring.datasource.url}
      user: ${SPRING_FLYWAY_USER}
      password: ${SPRING_FLYWAY_PASSWORD}
      schemas: apoia
      enabled: false

    ## Eureka
    eureka:
      client:
        #serviceUrl:
        #  defaultZone: https://discovery.stg.cloud.pje.jus.br/eureka
        enabled: false
      #instance:
      #  healthCheckUrlPath: /actuator/health
      #  statusPageUrlPath: /actuator/info
      #  homePageUrl: https://gateway.stg.cloud.pje.jus.br/apoia # <- url-base na marketplace
      #  metadataMap:
      #    pdpj: true # <- para ativar na marketplace

    ## PDPJ
    pdpj:
      appName: apoia
      nomeServico: ApoIA
      descricao: Inteligência Artificial Generativa
      iconePequenoUrl: https://apoia.stg.pdpj.jus.br/apoia-logo.svg
      iconeGrandeUrl: https://apoia.stg.pdpj.jus.br/apoia-logo.svg
      frontendUrl: https://apoia.stg.pdpj.jus.br
      gatewayUrl: https://apoia.stg.pdpj.jus.br
      swaggerUrl: https://apoia.stg.pdpj.jus.br/swagger-ui.html
      documentacaoUsuarioUrl: null
      documentacaoTecnicaUrl: null

    # configurações do actuator
    management:
      health:
        probes:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health,info
      metrics:
        export:
          prometheus:
            enabled: 'true'
      endpoint:
        health:
          show-details: always

    # opções de log
    logging:
      level:
        br.jus.pdpj: INFO