export const tua = {
    '2': 'PROCESSO CÍVEL E DO TRABALHO',
    '5': 'SUPERIOR TRIBUNAL DE JUSTIÇA',
    '7': 'Procedimento Comum Cível',
    '22': 'Procedimento Sumário',
    '26': 'Procedimentos Especiais',
    '27': 'Procedimentos Especiais de Jurisdição Contenciosa',
    '28': 'Anulação e Substituição de Títulos ao Portador',
    '29': 'Apreensão e Depósito de Coisa Vendida com Reserva de Domínio',
    '30': 'Arrolamento Comum',
    '31': 'Arrolamento Sumário',
    '32': 'Consignação em Pagamento',
    '34': 'Demarcação / Divisão',
    '35': 'Depósito',
    '37': 'Embargos de Terceiro Cível',
    '38': 'Habilitação',
    '39': 'Inventário',
    '40': 'Monitória',
    '41': 'Nunciação de Obra Nova',
    '44': 'Prestação de Contas - Oferecidas',
    '45': 'Ação de Exigir Contas',
    '46': 'Restauração de Autos Cível',
    '47': 'Ação Rescisória',
    '48': 'Sobrepartilha',
    '49': 'Usucapião',
    '50': 'Procedimentos Especiais de Jurisdição Voluntária',
    '51': 'Abertura, Registro e Cumprimento de Testamento',
    '52': 'Alienação Judicial de Bens',
    '53': 'Arrecadação das Coisas Vagas',
    '54': 'Confirmação de Testamento',
    '55': 'Declaração de Ausência',
    '56': 'Especialização de Hipoteca Legal',
    '57': 'Herança Jacente',
    '58': 'Interdição/Curatela',
    '59': 'Organização e Fiscalização de Fundação',
    '60': 'Separação Consensual',
    '61': 'Tutela e Curatela -  Nomeação',
    '62': 'Procedimentos Regidos por Outros Códigos, Leis Esparsas e Regimentos',
    '63': 'Ação Civil Coletiva',
    '64': 'Ação Civil de Improbidade Administrativa',
    '65': 'Ação Civil Pública',
    '66': 'Ação Popular',
    '69': 'Alimentos - Lei Especial Nº 5.478/68',
    '72': 'Alteração do Regime de Bens',
    '74': 'Alvará Judicial - Lei 6858/80',
    '76': 'Apreensão de Embarcações',
    '77': 'Arribadas Forçadas',
    '79': 'Regulação de Avaria Grossa',
    '80': 'Avarias',
    '81': 'Busca e Apreensão em Alienação Fiduciária',
    '82': 'Cancelamento de Naturalização',
    '83': 'Cautelar Fiscal',
    '84': 'Cobrança de Cédula de Crédito Industrial',
    '85': 'Compromisso Arbitral',
    '86': 'Consignatória de Aluguéis',
    '87': 'Conversão de Separação Judicial em Divórcio',
    '88': 'Correição Parcial ou Reclamação Correicional',
    '89': 'Depósito da Lei 8. 866/94',
    '90': 'Desapropriação',
    '91': 'Desapropriação Imóvel Rural por Interesse Social',
    '92': 'Despejo',
    '93': 'Despejo por Falta de Pagamento',
    '94': 'Despejo por Falta de Pagamento Cumulado Com Cobrança',
    '95': 'Direta de Inconstitucionalidade',
    '96': 'Discriminatória',
    '97': 'Dissolução e Liquidação de Sociedade',
    '98': 'Divórcio Consensual',
    '99': 'Divórcio Litigioso',
    '100': 'Dúvida',
    '107': 'Expropriação da Lei 8.257/91',
    '108': 'Falência de Empresários, Sociedades Empresáriais, Microempresas e Empresas de Pequeno Porte',
    '110': 'Habeas Data Cível',
    '111': 'Habilitação de Crédito',
    '112': 'Homologação de Transação Extrajudicial',
    '113': 'Imissão na Posse',
    '114': 'Impugnação de Crédito',
    '115': 'Inquérito Extrajudicial',
    '118': 'Mandado de Injunção',
    '119': 'Mandado de Segurança Coletivo',
    '120': 'Mandado de Segurança Cível',
    '121': 'Naturalização',
    '122': 'Opção de Nacionalidade',
    '123': 'Averiguação de Paternidade',
    '124': 'Pedido de Resposta ou Retificação da Lei de Imprensa',
    '127': 'Protesto Formado a Bordo',
    '128': 'Recuperação Extrajudicial',
    '129': 'Recuperação Judicial',
    '134': 'Registro Torrens',
    '135': 'Relatório Falimentar',
    '136': 'Remição do Imóvel Hipotecado',
    '137': 'Renovatória de Locação',
    '138': 'Restituição de Coisa ou Dinheiro na Falência do Devedor Empresário',
    '140': 'Revisional de Aluguel',
    '141': 'Separação Litigiosa',
    '142': 'Sonegados',
    '143': 'Suprimento de Idade e/ou Consentimento',
    '144': 'Suspensão de Liminar ou Antecipação de Tutela',
    '145': 'Suspensão de Execução de Sentença',
    '150': 'Procedimento de Liquidação',
    '151': 'Liquidação por Arbitramento',
    '152': 'Liquidação de Sentença pelo Procedimento Comum',
    '153': 'Liquidação Provisória por Arbitramento',
    '154': 'Liquidação Provisória de Sentença pelo Procedimento Comum',
    '155': 'Procedimento de Cumprimento de Sentença/Decisão',
    '156': 'Cumprimento de sentença',
    '157': 'Cumprimento Provisório de Sentença',
    '158': 'Processo de Execução',
    '159': 'Execução de Título Extrajudicial',
    '165': 'Insolvência Civil',
    '166': 'Insolvência Requerida pelo Credor',
    '167': 'Insolvência Requerida pelo Devedor ou pelo Espólio',
    '169': 'Embargos',
    '170': 'Embargos à Adjudicação',
    '171': 'Embargos à Arrematação',
    '172': 'Embargos à Execução',
    '173': 'Embargos de Retenção por Benfeitorias',
    '175': 'Processo Cautelar',
    '176': 'Alimentos - Provisionais',
    '177': 'Apreensão de  Títulos',
    '178': 'Arresto ',
    '179': 'Arrolamento de Bens',
    '180': 'Atentado',
    '181': 'Busca e Apreensão',
    '182': 'Caução',
    '183': 'Cautelar Inominada',
    '186': 'Exibição',
    '188': 'Homologação do Penhor Legal',
    '190': 'Justificação',
    '191': 'Protesto',
    '192': 'Posse em Nome do Nascituro',
    '193': 'Produção Antecipada da Prova',
    '194': 'Regulamentação de Visitas',
    '195': 'Separação de Corpos',
    '196': 'Seqüestro',
    '197': 'Recursos',
    '198': 'Apelação Cível',
    '199': 'Remessa Necessária Cível',
    '200': 'Agravos',
    '202': 'Agravo de Instrumento',
    '203': 'Agravo de Instrumento em Recurso Especial',
    '204': 'Agravo de Instrumento em Recurso Extraordinário',
    '206': 'Agravo Regimental Cível',
    '207': 'Embargos',
    '208': 'Embargos Infringentes',
    '210': 'Embargos Infringentes na Execução Fiscal',
    '211': 'Recurso Ordinário Cível',
    '212': 'Recurso Extraordinário',
    '213': 'Recurso Especial',
    '214': 'Outros Procedimentos',
    '215': 'Incidentes',
    '216': 'Incidente De Arguição de Inconstitucionalidade Cível',
    '218': 'Assistência Judiciária',
    '221': 'Conflito de competência cível',
    '224': 'Exceções',
    '228': 'Exibição de Documento ou Coisa Cível',
    '229': 'Impugnação ao Cumprimento de Sentença',
    '230': 'Impugnação ao Pedido de Assistência Litisconsorcial ou Simples',
    '231': 'Impugnação ao Valor da Causa Cível',
    '232': 'Incidente de Falsidade',
    '233': 'Incidente de Uniformização de Jurisprudência',
    '234': 'Remoção de Inventariante',
    '236': 'Oposição',
    '237': 'Atos e expedientes',
    '238': 'Avocatória',
    '239': 'Habilitação para Casamento',
    '240': 'Instrução de Rescisória',
    '241': 'Petição Cível',
    '242': 'Comunicação',
    '244': 'Reclamação',
    '251': 'Registro de Casamento Nuncupativo',
    '256': 'Representação por Excesso de Prazo',
    '257': 'Cartas',
    '258': 'Carta de Ordem Cível',
    '261': 'Carta Precatória Cível',
    '264': 'Carta Rogatória Cível',
    '268': 'PROCESSO CRIMINAL',
    '269': 'Medidas Preparatórias',
    '270': 'Notícia-Crime',
    '271': 'Representação Criminal',
    '272': 'Representação Criminal/Notícia de Crime',
    '273': 'Pedido de Arquivamento em Representação Criminal',
    '274': 'Interpelações',
    '275': 'Notificação para Explicações',
    '276': 'Notificação para Explicações (Lei de Imprensa)',
    '277': 'Procedimentos Investigatórios',
    '278': 'Termo Circunstanciado',
    '279': 'Inquérito Policial',
    '280': 'Auto de Prisão em Flagrante',
    '281': 'Procedimento Comum',
    '282': 'Ação Penal de Competência do Júri',
    '283': 'Ação Penal - Procedimento Ordinário',
    '284': 'Processo Especial',
    '285': 'Processo Especial do Código de Processo Penal',
    '287': 'Crimes de Responsabilidade dos Funcionários Públicos',
    '288': 'Crimes de Calúnia, Injúria e Difamação de Competência do Juiz Singular',
    '289': 'Crimes Contra a Propriedade Imaterial',
    '290': 'Processo Sumário (Detenção)',
    '291': 'Restauração de Autos Criminal',
    '292': 'Processo Especial de Leis Esparsas',
    '293': 'Crimes Ambientais',
    '294': 'Crimes Contra a Propriedade Industrial',
    '295': 'Crimes Contra a Propriedade Intelectual',
    '297': 'Crimes de Imprensa',
    '299': 'Procedimento do Juizado Especial Criminal - Sumariíssimo',
    '300': 'Procedimento Especial da Lei Antitóxicos',
    '302': 'Procedimento Especial dos Crimes de Abuso de Autoridade',
    '303': 'Medidas Garantidoras',
    '304': 'Liberdade',
    '305': 'Liberdade Provisória com ou sem fiança',
    '306': 'Relaxamento de Prisão',
    '307': 'Habeas Corpus Criminal',
    '308': 'Medidas Cautelares',
    '309': 'Pedido de Busca e Apreensão Criminal',
    '310': 'Pedido de Quebra de Sigilo de Dados e/ou Telefônico',
    '311': 'Medidas Investigatórias Sobre Organizações Criminosas',
    '312': 'Pedido de Prisão',
    '313': 'Pedido de Prisão Preventiva',
    '314': 'Pedido de Prisão Temporária',
    '315': 'Pedido de Prisão/ Liberdade Vigiada para Fins de Expulsão',
    '316': 'Questões e Processos Incidentes',
    '317': 'Exceções',
    '318': 'Exceção de Suspeição',
    '319': 'Exceção de Incompetência de Juízo',
    '320': 'Exceção de Litispendência',
    '321': 'Exceção de Ilegitimidade de Parte',
    '322': 'Exceção de Coisa Julgada',
    '323': 'Exceção de Impedimento',
    '324': 'Exceção da Verdade',
    '325': 'Conflito de Jurisdição',
    '326': 'Restituição de Coisas Apreendidas',
    '327': 'Embargos de Terceiro Criminal',
    '328': 'Medidas Assecuratórias',
    '329': 'Seqüestro',
    '330': 'Arresto / Hipoteca Legal',
    '331': 'Incidentes',
    '332': 'Incidente de Falsidade',
    '333': 'Insanidade Mental do Acusado',
    '334': 'Cartas',
    '335': 'Carta de Ordem Criminal',
    '355': 'Carta Precatória Criminal',
    '375': 'Carta Rogatória Criminal',
    '385': 'EXECUÇÃO PENAL E DE MEDIDAS ALTERNATIVAS',
    '386': 'Execução da Pena',
    '406': 'Incidentes',
    '407': 'Conversão de Pena',
    '408': 'Excesso ou Desvio',
    '409': 'Anistia',
    '410': 'Indulto',
    '411': 'Comutação de Pena',
    '412': 'Recursos',
    '413': 'Agravo de Execução Penal',
    '416': 'Apelação em Mandado de Segurança',
    '417': 'Apelação Criminal',
    '418': 'Carta Testemunhável',
    '419': 'Correição Parcial Criminal',
    '420': 'Embargos de Declaração Criminal',
    '421': 'Embargos Infringentes e de Nulidade',
    '422': 'Protesto por Novo Júri',
    '424': 'Recurso de Medida Cautelar Criminal',
    '425': 'Recurso de Sentença Criminal',
    '426': 'Recurso em Sentido Estrito',
    '427': 'Remessa Necessária Criminal',
    '428': 'Revisão Criminal',
    '432': 'Desaforamento de Julgamento',
    '433': 'Incidente de Uniformização de Jurisprudência',
    '436': 'Procedimento do Juizado Especial Cível',
    '457': 'Pedido de Uniformização de Interpretação de Lei Cível',
    '460': 'Recurso Inominado Cível',
    '547': 'PROCEDIMENTOS DE INFÂNCIA E JUVENTUDE',
    '976': 'Ação Anulatória de Cláusulas Convencionais',
    '980': 'Ação de Cumprimento',
    '985': 'Ação Trabalhista - Rito Ordinário',
    '986': 'Inquérito para Apuração de Falta Grave',
    '987': 'Dissídio Coletivo',
    '988': 'Dissídio Coletivo de Greve',
    '990': 'Execução de Título Extrajudicial',
    '991': 'Execução de Termo de Ajuste de Conduta',
    '992': 'Execução de Termo de Conciliação de CCP',
    '993': 'Execução de Certidão de Crédito Judicial',
    '994': 'Execução Provisória em Autos Suplementares',
    '1000': 'Agravo',
    '1001': 'Agravo de Instrumento em Agravo de Petição',
    '1002': 'Agravo de Instrumento em Recurso de Revista',
    '1003': 'Agravo de Instrumento em Recurso Ordinário',
    '1004': 'Agravo de Petição',
    '1005': 'Agravo Regimental Trabalhista',
    '1006': 'Embargos',
    '1007': 'Embargos Infringentes',
    '1008': 'Recurso de Revista',
    '1009': 'Recurso Ordinário Trabalhista',
    '1013': 'Agravo em Recurso de Habeas Corpus',
    '1015': 'Embargos de Divergência em Recurso de Mandado de Segurança',
    '1016': 'Embargos de Divergência em Agravo Regimental',
    '1017': 'Embargos à Execução em Mandado de Segurança',
    '1018': 'Embargos à Execução em Ação Recisoria',
    '1019': 'Embargos à Execução em Medida Cautelar',
    '1020': 'Execução em Ação Rescisória',
    '1021': 'Execução em Sentença Estrangeira',
    '1022': 'Execução em Sentença Estrangeira Contestada',
    '1023': 'Execução em Mandado de Segurança',
    '1024': 'Execução em Medida Cautelar',
    '1025': 'Incidente de Deslocamento de Competência ',
    '1026': 'Homologação de Decisão Estrangeira',
    '1027': 'Sentença Estrangeira Contestada',
    '1028': 'Sindicância',
    '1029': 'Mandado de Segurança',
    '1030': 'Reclamação',
    '1031': 'Recurso Ordinário',
    '1032': 'Recurso Especial',
    '1033': 'Ação Penal',
    '1034': 'Interpelação Judicial',
    '1035': 'Apelação Cível',
    '1036': 'Suspensão de Liminar e de Sentença',
    '1037': 'Embargos Infringentes em Apelação Cível',
    '1038': 'Representação',
    '1040': 'Requisição de Pequeno Valor',
    '1042': 'Inquérito',
    '1044': 'Agravo de Instrumento',
    '1045': 'Agravo em Recurso Extraordinário',
    '1046': 'Agravo em Recurso de Mandado de Segurança',
    '1047': 'Carta Rogatória',
    '1049': 'Habeas Data',
    '1053': 'Conflito de Atribuição',
    '1054': 'Conflito de Competência',
    '1057': 'Petição',
    '1062': 'Medida Cautelar',
    '1063': 'Exceção da Verdade',
    '1064': 'Remessa Necessária em Habeas Corpus',
    '1066': 'Embargos Infringentes em Ação Rescisória',
    '1067': 'Procedimentos Trabalhistas',
    '1068': 'Processo de Execução Trabalhista',
    '1070': 'Incidentes Trabalhistas',
    '1071': 'Recursos Trabalhistas',
    '1072': 'Pedido de Revisão do Valor da Causa',
    '1106': 'Processo de Conhecimento',
    '1107': 'Procedimento de Conhecimento',
    '1111': 'Execução de Título Judicial',
    '1112': 'Execução de Alimentos',
    '1114': 'Execução Contra a Fazenda Pública',
    '1116': 'Execução Fiscal',
    '1117': 'Execução Hipotecária do Sistema Financeiro da Habitação',
    '1118': 'Embargos à Execução Fiscal',
    '1122': 'Tutela e Curatela - Remoção e Dispensa',
    '1124': 'Justificação de Dinheiro a Risco',
    '1125': 'Ação Trabalhista - Rito Sumaríssimo',
    '1126': 'Ação Trabalhista - Rito Sumário (Alçada)',
    '1137': 'Embargos de Divergência em Recurso Especial',
    '1145': 'Conflito de Competência',
    '1178': 'Incidente de Arguição de Inconstitucionalidade Criminal',
    '1198': 'PROCEDIMENTOS ADMINISTRATIVOS',
    '1199': 'Pedido de Providências',
    '1202': 'Reclamação',
    '1208': 'Agravo Interno Cível',
    '1209': 'Agravos',
    '1230': 'Exceção de Impedimento',
    '1231': 'Exceção de Suspeição',
    '1232': 'Exceção de Incompetência',
    '1233': 'Efeito Suspensivo',
    '1262': 'Processo Administrativo Disciplinar em face de Servidor',
    '1264': 'Processo Administrativo Disciplinar em face de Magistrado',
    '1265': 'Precatório',
    '1266': 'Requisição de Pequeno Valor',
    '1267': 'Recurso de Multa',
    '1268': 'Medidas Protetivas de Urgência (Lei Maria da Penha)  - Criminal',
    '1269': 'Habeas Corpus Cível',
    '1271': 'Recurso de Medida Cautelar Cível',
    '1283': 'Superveniência de doença mental',
    '1284': 'Unificação de penas',
    '1285': 'Conflito de atribuição',
    '1288': 'Transferência entre estabelecimentos penais',
    '1289': 'Outras medidas provisionais',
    '1291': 'Reabilitação',
    '1294': 'Outros procedimentos de jurisdição voluntária',
    '1295': 'Alvará Judicial',
    '1296': 'Declaratória de Constitucionalidade',
    '1297': 'Intervenção em Município',
    '1298': 'Processo Administrativo',
    '1299': 'Recurso Administrativo',
    '1301': 'Reclamação Disciplinar',
    '1303': 'Correição Extraordinária',
    '1304': 'Inspeção',
    '1306': 'Recurso em Processo Administrativo Disciplinar em face de Servidor',
    '1307': 'Correição Ordinária',
    '1308': 'Sindicância',
    '1310': 'SUPREMO TRIBUNAL FEDERAL',
    '1311': 'Ação Cautelar',
    '1312': 'Ação  Originária',
    '1313': 'Ação Declaratória de Constitucionalidade',
    '1314': 'Ação Direta de Inconstitucionalidade',
    '1315': 'Ação Cível Originária',
    '1316': 'Ação Originária Especial',
    '1317': 'Ação Penal',
    '1318': 'Ação Rescisória',
    '1319': 'Agravo Interno',
    '1320': 'Agravo de Instrumento',
    '1321': 'Agravo Regimental',
    '1322': 'Arguição de Descumprimento de Preceito Fundamental',
    '1323': 'Arguição de Suspeição',
    '1324': 'Carta Rogatória',
    '1325': 'Comunicação',
    '1326': 'Conflito de Competência',
    '1327': 'Embargos de Declaração',
    '1328': 'Embargos Divergentes',
    '1329': 'Embargos Infringentes',
    '1330': 'Extradição',
    '1331': 'Habeas Corpus',
    '1332': 'Habeas Data',
    '1333': 'Inquerito',
    '1334': 'Intervenção Federal',
    '1335': 'Mandado de Injunção',
    '1336': 'Mandado de Segurança',
    '1337': 'Medida Cautelar',
    '1338': 'Petição',
    '1339': 'Prisão Preventiva para Extradição',
    '1340': 'Processo Administrativo',
    '1341': 'Questão de Ordem',
    '1342': 'Reclamação',
    '1343': 'Recurso Criminal',
    '1344': 'Recurso em Habeas Corpus',
    '1345': 'Recurso em Habeas Data',
    '1346': 'Recurso em Mandado de Injunção',
    '1347': 'Recurso em Mandado de Segurança',
    '1348': 'Recurso Extraordinário',
    '1349': 'Revisão Criminal',
    '1350': 'Sentença Estrangeira',
    '1351': 'Sentença Estrangeira Contestada',
    '1352': 'Suspensão de Liminar',
    '1353': 'Suspensão de Segurança',
    '1354': 'Suspensão de Tutela Provisória',
    '1355': 'Siglas dos Processos Extintos',
    '1356': 'Ação Ordinária Regressiva',
    '1357': 'Ação Regressiva',
    '1358': 'Apelação Cível',
    '1359': 'Apelação Criminal',
    '1360': 'Arguição de Relevância',
    '1361': 'Carta Testemunhável',
    '1362': 'Conflito de Atribuições',
    '1363': 'Conflito de Jurisdição',
    '1364': 'Denúncia',
    '1365': 'Embargos Remetidos',
    '1366': 'Exceção da Verdade',
    '1367': 'Exceção de Suspeição',
    '1368': 'Inquérito Administrativo',
    '1369': 'Inquérito Policial',
    '1370': 'Inquérito Policial Especial',
    '1371': 'Interpelação',
    '1372': 'Liquidação de Sentença',
    '1373': 'Notificação',
    '1374': 'Pedido de Avocação',
    '1375': 'Processo Crime',
    '1376': 'Processo Judicial',
    '1377': 'Queixa Crime',
    '1378': 'Recurso de Apreensão de Livro',
    '1379': 'Recurso de Liquidação de Sentença',
    '1380': 'Recurso de Revista',
    '1381': 'Representação',
    '1382': 'Retificação de Nome Estrangeiro',
    '1383': 'Sentença Arbitral',
    '1384': 'Suspensão de Direitos',
    '1385': 'Seção Cível',
    '1386': 'Processo de Conhecimento',
    '1389': 'Ação de Alimentos de Infância e Juventude',
    '1390': 'Revisão Judicial de Decisão do Conselho Tutelar',
    '1391': 'Apuração de Irregularidades em Entidades de Atendimento',
    '1392': 'Apuração de Infração Administrativa às Normas de Proteção à Criança ou Adolescente',
    '1396': 'Tutela Infância e Juventude',
    '1399': 'Tutela c/c Destituição do Poder Familiar',
    '1401': 'Adoção',
    '1412': 'Adoção c/c Destituição do Poder Familiar',
    '1414': 'Suprimento de Capacidade ou de Consentimento para Casar',
    '1415': 'Emancipação',
    '1417': 'Regularização de Registro Civil',
    '1420': 'Guarda de Infância e Juventude',
    '1424': 'Providência ',
    '1425': 'Prestação de Contas Infância e Juventude',
    '1426': 'Perda ou Suspensão do Poder Familiar',
    '1430': 'Processo de Execução',
    '1432': 'Execução de Alimentos Infância e Juventude',
    '1434': 'Execução de Medida de Proteção à Criança e Adolescente',
    '1435': 'Execução de Multa',
    '1436': 'Processos Cautelares',
    '1438': 'Busca e Apreensão Infância e Juventude',
    '1440': 'Cautelar Inominada Infância e Juventude',
    '1450': 'Cartas',
    '1451': 'Carta de Ordem Infância e Juventude',
    '1455': 'Carta Precatória Infância e Juventude',
    '1459': 'Seção Infracional',
    '1460': 'Procedimentos Investigatórios',
    '1461': 'Auto de Apreensão em Flagrante',
    '1462': 'Relatório de Investigações',
    '1463': 'Boletim de Ocorrência Circunstanciada',
    '1464': 'Processo de Apuração de Ato Infracional',
    '1465': 'Execução de Medidas Socioeducativas',
    '1466': 'Internação com Atividades Externas',
    '1467': 'Internação sem Atividades Externas',
    '1468': 'Semiliberdade',
    '1469': 'Liberdade Assistida',
    '1470': 'Prestação de Serviços a Comunidade',
    '1471': 'Obrigação de Reparar o Dano',
    '1472': 'Advertência ',
    '1473': 'Cartas',
    '1474': 'Carta de Ordem Infracional',
    '1478': 'Carta Precatória Infracional',
    '1669': 'Ação Rescisória',
    '1670': 'Ação de Improbidade Administrativa',
    '1671': 'Comunicação',
    '1672': 'Exceção de Impedimento',
    '1673': 'Exceção de Suspeição',
    '1674': 'Intervenção Federal',
    '1675': 'Mandado de Injunção',
    '1677': 'Precatório',
    '1678': 'Revisão Criminal',
    '1679': 'Suspensão de Segurança',
    '1680': 'Consulta Administrativa',
    '1682': 'Retificação ou Suprimento ou Restauração de Registro Civil',
    '1683': 'Retificação de Registro de Imóvel',
    '1685': 'Remessa Necessária Trabalhista',
    '1689': 'Embargos de Declaração Cível',
    '1690': 'Ação Civil Pública Infância e Juventude',
    '1691': 'Mandado de Segurança Infância e Juventude Cível',
    '1701': 'Nomeação de Advogado',
    '1702': 'Impugnação de Assistência Judiciária',
    '1703': 'Autorização judicial',
    '1704': 'Embargos de Terceiro Infância e Juventude',
    '1705': 'Remoção, modificação  e dispensa de tutor ou curador',
    '1706': 'Procedimento Comum Infância e Juventude',
    '1707': 'Reintegração / Manutenção de Posse',
    '1709': 'Interdito Proibitório',
    '1710': 'Mandado de Segurança Criminal',
    '1711': 'Agravo de Instrumento em Recurso Especial',
    '1712': 'Agravo de Instrumento em Recurso Extraordinário',
    '1714': 'Execução Provisória',
    '1715': 'Embargos do Acusado',
    '1717': 'Alienação de Bens do Acusado',
    '1719': 'Avaliação para atestar dependência de drogas',
    '1720': 'Habeas Corpus',
    '1721': 'Recurso Ordinário em Mandado de Segurança',
    '1722': 'Recurso Ordinário em Habeas Corpus',
    '1723': 'Contraprotesto Judicial',
    '1725': 'Notificação',
    '1726': 'Interpelação',
    '1727': 'Petição Criminal',
    '1728': 'Apelação / Remessa Necessária',
    '1729': 'Agravo Interno Criminal',
    '1730': 'Recurso Ordinário Criminal',
    '1731': 'Investigação contra magistrado',
    '1733': 'Procedimento Investigatório Criminal (PIC-MP) ',
    '10933': 'Habilitação para Adoção',
    '10942': 'Correição Parcial Cível',
    '10943': 'Ação Penal - Procedimento Sumário',
    '10944': 'Ação Penal - Procedimento Sumaríssimo',
    '10960': 'Incidente de Sanidade Mental',
    '10967': 'Medidas de Proteção à Pessoa Idosa - Criminal',
    '10969': 'Incidentes',
    '10970': 'Conflito de Competência Infância e Juventude',
    '10971': 'Exceções',
    '10972': 'Exibição de Documento ou Coisa Infância e Juventude',
    '10973': 'Impugnação ao Valor da Causa Infância e Juventude',
    '10974': 'Incidente de Falsidade Infância e Juventude',
    '10975': 'Exceção de Impedimento Infância e Juventude',
    '10976': 'Exceção de Incompetência Infância e Juventude',
    '10977': 'Exceção de Suspeição Infância e Juventude',
    '10979': 'Petição Infracional',
    '10980': 'Cumprimento Provisório de Decisão',
    '10981': 'Impugnação ao Cumprimento  de Decisão',
    '11026': 'Petição Infância e Juventude Cível',
    '11027': 'Remessa Necessária / Recurso Ordinário',
    '11028': 'PROCESSO MILITAR',
    '11029': 'PROCEDIMENTOS ESPECIAIS PREVISTOS EM LEIS ESPARSAS',
    '11030': 'PROCESSO CRIMINAL',
    '11031': 'Procedimento Especial',
    '11032': 'Procedimentos Investigatórios',
    '11033': 'Recursos',
    '11034': 'Conselho de Justificação ',
    '11035': 'Representação p/ Declaração de Indignidade/Incompatibilidade ',
    '11036': 'Representação p/ Perda da Graduação ',
    '11037': 'Ação Penal Militar - Procedimento Ordinário',
    '11038': 'Embargos em Ação Penal Militar',
    '11039': 'Reclamação Militar',
    '11040': 'Recurso Inominado Militar',
    '11041': 'Inquérito Policial Militar',
    '11042': 'Correição Parcial Militar',
    '11043': 'Deserção',
    '11044': 'Insubmissão',
    '11045': 'Deserção de Oficial',
    '11046': 'Deserção de Praça',
    '11099': 'PROCEDIMENTOS PRÉ-PROCESSUAIS DE RESOLUÇÃO CONSENSUAL DE CONFLITOS',
    '11397': 'Extinção das obrigações do falido',
    '11398': 'Recurso em sentido estrito/Recurso ex officio',
    '11399': 'Execução de Medida de Segurança',
    '11400': 'Agravo de Instrumento em Recurso Ordinário para o STF',
    '11427': 'PROCESSO ELEITORAL',
    '11525': 'Processos Cíveis-Eleitorais',
    '11526': 'Ação de Impugnação de Mandato Eletivo',
    '11527': 'Ação de Investigação Judicial Eleitoral',
    '11528': 'Ação Penal Eleitoral',
    '11529': 'Procedimentos Relativos a Realização de Eleição',
    '11530': 'Apuração de Eleição',
    '11531': 'Prestação de Contas',
    '11532': 'Registro de Candidatura',
    '11533': 'Recurso contra Expedição de Diploma',
    '11534': 'Procedimentos Relativos a Partidos Políticos',
    '11535': 'Cancelamento de Registro de Partido Político',
    '11536': 'Propaganda Partidária',
    '11537': 'Registro de Órgão de Partido Político em Formação',
    '11538': 'Registro de Comitê Financeiro',
    '11539': 'Registro de Partido Político',
    '11540': 'Procedimentos Administrativos da Justiça Eleitoral',
    '11541': 'Representação',
    '11542': 'Correição',
    '11543': 'Criação de Zona Eleitoral ou Remanejamento',
    '11544': 'Instrução',
    '11545': 'Lista Tríplice',
    '11546': 'Revisão de Eleitorado',
    '11547': 'Recursos Eleitorais',
    '11548': 'Recurso Eleitoral',
    '11549': 'Recurso Especial Eleitoral',
    '11550': 'Recurso Ordinário Eleitoral',
    '11551': 'Consulta',
    '11552': 'Pedido de Desaforamento',
    '11553': 'Instrução Provisória de Deserção',
    '11555': 'Suspensão de Liminar e de Sentença',
    '11556': 'Suspensão de Segurança Cível',
    '11787': 'Assistência Judiciária',
    '11788': 'Exibição de Documento ou Coisa Criminal',
    '11789': 'Impugnação ao Valor da Causa',
    '11790': 'Impugnação de Assistência Judiciária',
    '11791': 'Pedido de Uniformização de Interpretação de Lei Criminal',
    '11793': 'Produção Antecipada de Provas Criminal',
    '11794': 'Restituição de Coisas Apreendidas Infracional',
    '11798': 'Processo de Aplicação de Medida de Segurança Por Fato Não Criminoso',
    '11799': 'Instrução Provisória de Insubmissão',
    '11800': 'Instrução Provisória de Deserção',
    '11875': 'Reclamação Pré-processual',
    '11880': 'Recurso Extraordinário com Agravo',
    '11881': 'Agravo em Recurso Especial',
    '11882': 'Recurso de Revista com Agravo',
    '11886': 'Recurso Ordinário - Rito Sumaríssimo',
    '11887': 'Acompanhamento de Cumprimento de Decisão',
    '11888': 'Ato Normativo',
    '11889': 'Nota Técnica',
    '11890': 'Parecer de Mérito sobre Anteprojeto de Lei',
    '11891': 'Procedimento de Controle Administrativo',
    '11892': 'Revisão Disciplinar',
    '11893': 'Reclamação para Garantia das Decisões',
    '11894': ' Comissão',
    '11953': 'Arguição de Suspeição e de Impedimento',
    '11955': 'Cautelar Inominada Criminal',
    '11956': 'Embargos de Divergência em Agravo em Recurso Especial',
    '11957': 'Remição de Pena',
    '11976': 'Pedido de Busca e Apreensão Infracional',
    '12057': 'Reexame Necessário Eleitoral',
    '12058': 'Suspensão de Segurança',
    '12059': 'Suspensão de Segurança - Eleitoral',
    '12060': 'Incidente de Impedimento/Suspeição',
    '12061': 'Ação Cautelar',
    '12070': 'Pedido de Medida de Proteção',
    '12071': 'Procedimentos Cautelares',
    '12072': 'Busca e Apreensão Infracional',
    '12073': 'Internação Provisória',
    '12074': 'Pedido De Desinternação/Reavaliação/Substituição/Suspensão da Medida',
    '12075': 'Procedimento Conciliatório',
    '12076': 'Restabelecimento do Poder Familiar',
    '12077': 'Homologação em Acordo de Colaboração Premiada',
    '12078': 'Cumprimento de Sentença contra a Fazenda Pública',
    '12079': 'Execução de Título Extrajudicial contra a Fazenda Pública',
    '12080': 'Incidente de Impedimento Cível',
    '12081': 'Incidente de Suspeição Cível',
    '12082': 'Carta Arbitral',
    '12083': 'Tutela Antecipada Antecedente',
    '12084': 'Tutela Cautelar Antecedente',
    '12085': 'Incidente de Resolução de Demandas Repetitivas',
    '12086': 'Dissolução Parcial de Sociedade',
    '12087': 'Incidente de Assunção de Competência',
    '12088': 'Liquidação Provisória de Sentença pelo Procedimento Comum',
    '12089': 'Renovação de Permanência em Estabelecimento Penal Federal',
    '12117': 'Suspensão do Incidente de Resolução de Demandas Repetitivas',
    '12118': 'Suspensão em Incidente de Resolução de Demandas Repetitivas',
    '12119': 'Incidente de Desconsideração de Personalidade Jurídica',
    '12120': 'Agravo em Execução de Medidas Sócio-Educativas',
    '12121': 'Comunicado de Mandado de Prisão',
    '12122': 'Reclamação Criminal',
    '12123': 'Roteiro de Pena',
    '12124': 'Roteiro de Pena',
    '12125': 'Progressão de Regime',
    '12126': 'Regressão de Regime',
    '12127': 'Remição',
    '12128': 'Livramento Condicional',
    '12129': 'Outros Incidentes de Execução Iniciados de Ofício',
    '12132': 'Incidente de Julgamento de Recurso de Revista e de Embargos Repetitivos',
    '12133': 'Tutela Provisória de Urgência e Tutela Provisória de Evidência',
    '12134': 'Tutela Cautelar Antecedente',
    '12135': 'Tutela Antecipada Antecedente',
    '12136': 'Pedido de Mediação Pré-Processual',
    '12137': 'Requerimento de Apreensão de Veículo',
    '12138': 'Requerimento de Reintegração de Posse',
    '12139': 'Contestação em Foro Diverso',
    '12153': 'Embargos Parciais à Ação Monitória',
    '12154': 'Execução de Título Extrajudicial',
    '12190': 'Suspensão Nacional do Incidente de Resolução de Demandas Repetitivas',
    '12191': 'Tutela Provisória Antecedente',
    '12192': 'Tutela Provisória Incidental',
    '12193': 'Prestação de Contas Eleitorais',
    '12226': 'Notificação',
    '12227': 'Interpelação',
    '12228': 'Protesto',
    '12229': 'Protesto formado a bordo',
    '12230': 'Guarda c/c destituição do poder familiar',
    '12231': 'Cumprimento de sentença - Lei Arbitral (Lei 9.307/1996)',
    '12232': 'Ação de Partilha',
    '12233': 'Tutela Cível',
    '12234': 'Curatela',
    '12246': 'Cumprimento de Sentença de Obrigação de Prestar Alimentos',
    '12247': 'Execução Extrajudicial de Alimentos',
    '12248': 'Pedido de Cooperação Judiciária',
    '12249': 'Suspensão em IRDR',
    '12250': 'Suspensão em IRDR',
    '12251': 'Execução de Título Judicial - CEJUSC',
    '12357': 'Pedido de Efeito Suspensivo à Apelação',
    '12369': 'Tomada de Decisão Apoiada',
    '12370': 'Tomada de Decisão Apoiada',
    '12371': 'Alteração de Regime de Bens',
    '12372': 'Divórcio Consensual',
    '12373': 'Divórcio Litigioso',
    '12374': 'Homologação da Transação Extrajudicial',
    '12375': 'Reclamação',
    '12376': 'Regulação de Avaria Grossa',
    '12377': 'Prestação de Contas Anual',
    '12386': 'Incidente de Impedimento Infância e Juventude',
    '12388': 'Incidente de Suspeição Infância e Juventude',
    '12389': 'Ação de Partilha',
    '12390': 'ação de partilha',
    '12391': 'Incidente de Uniformização de Jurisprudência',
    '12394': 'Revisão Criminal',
    '12423': 'Medidas Protetivas de Urgência (Lei Maria da Penha) - Infracional',
    '12424': 'Medidas de Proteção à Pessoa Idosa - Infracional',
    '12464': 'Corregedoria Eleitoral',
    '12465': 'Petição Corregedoria',
    '12466': 'Inquérito Administrativo',
    '12541': 'Divórcio Litigioso',
    '12549': 'Cancelamento de Inscrição Eleitoral (CIE)',
    '12550': 'Composição de Mesa Receptora',
    '12551': 'Descarte de Material',
    '12552': 'Direitos Políticos',
    '12553': 'Duplicidade/Pluralidade de Inscrições - Coincidências',
    '12554': 'Filiação Partidária',
    '12555': 'Impugnação à Composição de Junta Eleitoral',
    '12556': 'Impugnação Perante as Juntas Eleitorais',
    '12557': 'Recurso/Impugnação de Alistamento Eleitoral',
    '12558': 'Registro de Debates',
    '12559': 'Regularização de Situação do Eleitor',
    '12560': 'Lista de Apoiamento para Criação de Partido Político',
    '12561': 'Notícia de Irregularidade em Propaganda Eleitoral',
    '12562': 'PET-ADM',
    '12613': 'Pedido de Conciliação Pré-Processual',
    '12625': 'Direito de Resposta',
    '12626': 'Agravo em Recurso Especial Eleitoral',
    '12627': 'Ação Rescisória Eleitoral',
    '12628': 'Ação de Justificação de Desfiliação Partidária/Perda de Cargo Eletivo',
    '12629': 'Pedido de Novas Eleições',
    '12630': 'Representação Especial',
    '12631': 'Requerimento de Regularização de Omissão de Prestação de Contas Anual',
    '12632': 'Requerimento de Regularização de Omissão de Prestação de Contas Anual',
    '12633': 'Requerimento de Regularização de Omissão de Prestação de Contas Eleitorais',
    '12727': 'Execução de Pena de Multa',
    '12728': 'Transferência Entre Estabelecimentos Penais',
    '12729': 'Execução de Medidas Alternativas no Juízo Comum',
    '12760': 'Recurso de Julgamento Parcial ',
    '12761': 'Homologação do Penhor Legal',
    '12762': 'Extinção Consensual de União Estável',
    '12763': 'Reconhecimento e Extinção de União Estável',
    '12764': 'Separação Contenciosa',
    '12775': 'Ação Direta de Inconstitucionalidade por Omissão',
    '12776': 'Arguição de Impedimento',
    '12777': 'Exceção de Incompetência',
    '12778': 'Exceção de Litispendência',
    '12779': 'Proposta de Súmula Vinculante',
    '12780': 'Admissão de Assistente',
    '12781': 'Impugnação ao Valor da Causa',
    '12782': 'Incidente de Falsidade',
    '12783': 'Oposição',
    '12784': 'Suspeição de Perito',
    '12785': 'Embargos à Execução',
    '12786': 'Cumprimento de Sentença',
    '12787': 'Execução contra a Fazenda Pública',
    '12788': 'Execução contra a Fazenda Pública',
    '12789': 'Execução de Pena',
    '12790': 'Extensão',
    '12791': 'Incidente de Assunção de Competência',
    '14123': 'Destinação de Bens Apreendidos',
    '14208': 'Suspensão de Órgão Partidário',
    '14209': 'Recurso Criminal Eleitoral',
    '14671': 'Guarda de Família',
    '14676': 'Pedido de Inclusão no Cadastro de Programa de Apadrinhamento',
    '14677': 'Regulamentação de Visitas',
    '14678': 'Acordo de Não Persecução Penal',
    '14695': 'Procedimento do Juizado Especial da Fazenda Pública',
    '14696': 'Execução de Medidas Alternativas nos Juizados Especiais',
    '14701': 'Habeas Data Criminal',
    '14734': 'Medidas de Proteção - Criança e Adolescente (Lei 13.431) Criminais',
    '14774': 'Agravo de Instrumento em Mandado de Segurança',
    '14775': 'Agravo de Instrumento em Mandado de Segurança',
    '14990': 'Classificação de Crédito Público',
    '14991': 'Classificação de Crédito Público',
    '15011': 'Registro de Federação Partidária',
    '15090': 'Recurso',
    '15140': 'Entrega Voluntária',
    '15159': 'Regime Centralizado de Execuções',
    '15160': 'Cumprimento de Sentença de Ações Coletivas',
    '15161': 'Cumprimento Provisório de Sentença de Ações Coletivas',
    '15167': 'Acordo de Não Persecução Cível',
    '15170': 'Medidas Protetivas de Urgência - Crianças e Adolescentes (Lei Henry Borel - Lei 14.344/2022) Criminais',
    '15171': 'Medidas Protetivas de Urgência - Crianças e Adolescentes (Lei Henry Borel - Lei 14.344/2022) Infracionais',
    '15172': 'Medidas de Proteção - Criança e Adolescente (Lei 13.431) Infracionais',
    '15187': 'Plano Especial de Pagamento Trabalhista',
    '15190': 'Destituição do Poder Familiar',
    '15191': 'Adoção pelo Cadastro',
    '15192': 'Adoção Fora do Cadastro',
    '15193': 'Adoção Fora do Cadastro c/c Destituição do Poder Familiar',
    '15194': 'Suspensão do Poder Familiar',
    '15195': 'Seção Administrativa',
    '15196': 'Inspeção',
    '15215': 'Cumprimento de Sentença contra a Fazenda Pública Mediante Execução Invertida',
    '15217': 'Procedimento de Repactuação de Dívidas (Superendividamento)',
    '15224': 'Habeas Corpus Coletivo',
    '15228': 'Queixa-Crime',
    '15239': 'Proposta de Anteprojeto de Lei',
    '15240': 'Auditoria',
    '15241': 'Avaliação de Obras',
    '15242': 'Pedido de Esclarecimento',
    '15243': 'Monitoramento de Auditorias e Obras',
    '15303': 'Representação em Propaganda Partidária',
    '15309': 'Medidas Protetivas de Urgência (Lei Maria da Penha) - Cível',
    '15321': 'Revisão Judicial - RDII',
    '15323': 'Reclamação Administrativa Eleitoral'
  }